modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/ClientTweaks/issues"

[[mods]]
modId="clienttweaks"
version="${file.jarVersion}"
displayName="Client Tweaks"
displayURL="https://blay09.net/mods/clienttweaks"
logoFile="clienttweaks-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
There, I fixed Minecraft for you. Various optional tweaks to improve Minecraft Quality of Life.
'''

[[dependencies.clienttweaks]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clienttweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clienttweaks]]
    modId="balm"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"
